from django.conf.urls import patterns, url
import views


urlpatterns = patterns('',
    url(r'^login/$', views.page),
    url(r'^page/$', views.login),
    url(r'^index/$',views.indexpage),
    url(r'^register/$',views.register),
    url(r'^logout/$', views.logout),
    url(r'^logout/$', views.logoutUser, name='logout'),
    url(r'^completeInfo/$', views.completeInfo, name='completeInfo'),
    url(r'^foyer/$', views.foyer, name='foyer'),
    url(r'^message/$', views.message, name='message'),
    url(r'^resources/$', views.resources, name='resources'),
    url(r'^ccc/$',views.ccc),
    url(r'^post/$',views.post),
    url(r'^ddd/$',views.ddd),
    url(r'^upflow/$',views.upflow),
    url(r'^upall/$',views.upall),
    url(r'^backdevice/$',views.backdevice),
    url(r'^backflow/$',views.backflow),
    url(r'^backcontrol/$',views.backcontrol),
    url(r'^eee/$',views.eee),
    url(r'^fff/$',views.fff),
    url(r'^ggg/$',views.ggg),
    url(r'^ajax/$',views.ajax),
    url(r'^upload/$',views.upload),
    url(r'^adjust/$',views.adjust),
    url(r'^scores/$', views.scores, name='scores'),
    url(r'^competitions/$', views.competitions, name='competitions'),
    url(r'^applyTeam/$', views.applyTeam, name='applyTeam'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^management/$', views.management, name='management'),
    url(r'^addResource/$', views.addResource, name='addResource'),
    url(r'^applyResource/(?P<resource_id>[a-z0-9]+)/$', views.applyResource, name='applyResource'),
    url(r'^replyResourceApplication/(?P<reply>[a-z]+)/(?P<application_id>[a-z0-9]+)/$', views.replyResourceApplication, name='replyResourceApplication'),
    url(r'^replyTeamApplication/(?P<reply>[a-z]+)/(?P<application_id>[a-z0-9]+)/$', views.replyTeamApplication, name='replyTeamApplication'),
    url(r'^deleteUser/(?P<username>[0-9]+)/$', views.deleteUser, name='deleteUser'),   
    url(r'^flow/$',views.flow_layer),
    url(r'^control/$',views.control_layer),
)
